app: nas
service: ip-retention-handler

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  environment:
    IP_SET_CONFIG_SSM_NAME: /nas/ipsets/config
    ALLOW_LIST_TABLE_NAME: AllowList
    ALLOW_LIST_REQUESTS_TABLE_NAME: AllowListRequests
  iam:
    role: arn:aws:iam::485515729987:role/nas-lambda-ip-expiry-handler-role
  region: us-east-1
  memorySize: 256
  deploymentBucket:
    serverSideEncryption: AES256
  # tags:

functions:
  function:
    name: nas-ip-retention-handler-${sls:stage}
    handler: lambda_function.lambda_handler # new
    memorySize: 1024
    timeout: 90